spring.application.name=slotsimulator

# データベースの接続設定
# ポート番号5432、データベース名slotgame_dbに繋ぎます
spring.datasource.url=jdbc:postgresql://localhost:5433/slotgame_db
spring.datasource.username=postgres
spring.datasource.password=artnerhr

# データベースのドライバ設定
spring.datasource.driver-class-name=org.postgresql.Driver

# テーブルを自動で作る設定
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true